apiVersion: v1
kind: Namespace
metadata:
  name: rook-edgefs-mec1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs-mec1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs-mec1
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
- apiGroups: ["edgefs.rook.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get", "list" ]
- apiGroups: ["extensions"]
  resources: ["deployments/scale"]
  verbs: [ "get", "update" ]
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster-mgmt
  namespace: rook-edgefs-mec1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-edgefs-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
# Allow the pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs-mec1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-edgefs-cluster
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs-mec1
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged-cluster-mec1
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-psp-user-cluster-mec1
rules:
- apiGroups:
  - apps
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged-cluster-mec1
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-system-psp-cluster-mec1
  namespace: rook-edgefs-mec1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user-cluster-mec1
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-cluster-mec1-psp
  namespace: rook-edgefs-mec1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user-cluster-mec1
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs-mec1
---
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs-mec1
  namespace: rook-edgefs-mec1
spec:
  edgefsImageName: edgefs/edgefs:1.2.83 # specify version here, i.e. edgefs/edgefs:1.1.0 etc
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  sysRepCount: 2                   # number of chunk replicas to keep. Overrides default one (3)
  failureDomain: "device"          # failure domain: "device", "host" or "zone". Overrides automatically calculated one
  commitNWait: 1                   # Write performance tuning
  storage:                         # cluster level storage configuration and selection
    useAllNodes: false
    directories:
    - path: "/media/nvme0n1"       # if the RTKVS is chosen, then the directory will be used as a journal to store metadata. Mandatory for RTKVS.
    useAllDevices: false
    config:
      useRtkvsBackend: "kvssd"     # Use the RTKVS engine. The "kvssd" is for Samsung's KV SSD
      rtPLevelOverride: "16"
      maxSizeGB: "32"              # RTKVS: max.space allocated for a journal
      sync: "0"                    # highest performance, consistent on pod/software failures
      walMode: "off"               # Write-ahead-log mode disable (KV SSD performance)
    nodes:
    - name: "samsung-kvssd"
      devices:
      - fullpath: "/dev/disk/by-id/nvme-SAMSUNG_MZQLB3T8HALS-000AZ_S3VJNA0M835008"
      - fullpath: "/dev/disk/by-id/nvme-SAMSUNG_MZQLB3T8HALS-000AZ_S3VJNA0M835010"
