apiVersion: v1
kind: Namespace
metadata:
  name: rook-edgefs-aggr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs-aggr
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs-aggr
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
- apiGroups: ["edgefs.rook.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get", "list" ]
- apiGroups: ["extensions"]
  resources: ["deployments/scale"]
  verbs: [ "get", "update" ]
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster-mgmt
  namespace: rook-edgefs-aggr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-edgefs-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
# Allow the pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs-aggr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-edgefs-cluster
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs-aggr
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged-cluster-aggr
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-psp-user-cluster-aggr
rules:
- apiGroups:
  - apps
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged-cluster-aggr
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-system-psp-cluster-aggr
  namespace: rook-edgefs-aggr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user-cluster-aggr
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-cluster-aggr-psp
  namespace: rook-edgefs-aggr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user-cluster-aggr
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs-aggr
---
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs-aggr
  namespace: rook-edgefs-aggr
spec:
  edgefsImageName: edgefs/edgefs:1.2.83 # specify version here, i.e. edgefs/edgefs:1.1.0 etc
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  sysRepCount: 2                  # number of chunk replicas to keep. Overrides default one (3)
  failureDomain: "device"           # failure domain: "device", "host" or "zone". Overrides automatically calculated one
  commitNWait: 1
  #devicesResurrectMode: "restoreZapWait"
  #dashboard:
  #  localAddr: 10.3.30.75
  #network: # cluster level networking configuration
  #  provider: host
  #  selectors:
  #    server: "enp2s0f0"
  #    broker: "enp2s0f0"
  #skipHostPrepare: true
  #trlogProcessingInterval: 2      # set transaction log processing interval to 2s to speed up ISGW Link delivery
  #trlogKeepDays: 2                # keep up to 2 days of transaction log interval batches to reduce local storage overhead
  #useHostLocalTime: true
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    directories:
    - path: "/media/sdd"
    - path: "/media/sde"                # if the RTKVS is chosen, then the directory will be used as a journal to store metadata. Mandatory for RTKVS.
    useAllDevices: false
    config:
      useRtkvsBackend: "kvssd"       # Use the RTKVS store driver. Value is the backend ID. The "kvssd" is for Samsung's KV SSD
      rtPLevelOverride: "16"       # enable large device partitioning, only needed if automatic not working
      maxSizeGB: "32"              # RTKVS: max.space allocated for a journal
      sync: "0"                    # highest performance, consistent on pod/software failures, not-consistent on power failures
      walMode: "off"               # Write-ahead-log mode. From a set: "on" - enabled, "off" - disabled, "metadata" - use the WAL for data type stored on the metadata SSD (RTKVS only)
    nodes:
    - name: "edgefs-aggr"
      devices:
      - fullpath: "/dev/disk/by-id/nvme-SAMSUNG_MZQLB3T8HALS-000AZ_S3VJNY0J600450"
      - fullpath: "/dev/disk/by-id/nvme-SAMSUNG_MZQLB3T8HALS-000AZ_S3VJNY0K303383"
  #resources:
  #  limits:
  #    cpu: "2"
  #    memory: "4096Mi"
  #  requests:
  #    cpu: "2"
  #    memory: "4096Mi"
  # A key value list of annotations
  #annotations:
  #  all:
  #    key: value
  #  mgr:
  #  prepare:
  #  target:
  #placement:
  #  all:
  #    nodeAffinity:
  #      requiredDuringSchedulingIgnoredDuringExecution:
  #        nodeSelectorTerms:
  #        - matchExpressions:
  #          - key: nodekey
  #            operator: In
  #            values:
  #            - edgefs-target
  #    tolerations:
  #    - key: taintKey
  #      operator: Exists
