apiVersion: edgefs.rook.io/v1
kind: NFS
metadata:
  name: nfs-aggr
  namespace: rook-edgefs-aggr
spec:
  instances: 1
  annotations:
---

apiVersion: edgefs.rook.io/v1
kind: ISGW
metadata:
  name: isgw-stream          # Inter-Segment Gateway link for on-demand video streams
  namespace: rook-edgefs-aggr
spec:
  direction: "send+receive"  # I/O flow direction: send, receive or send-receive
  remoteURL: "ccow://rook-edgefs-isgw-isgw-stream.rook-edgefs-mec1:14000"    # I/O flow with destination antoher EdgeFS cluster, pointing to ISGW endpoint service
  dynamicFetchAddr: rook-edgefs-isgw-isgw-stream.rook-edgefs-aggr:49678      # Dynamic fetch service host:port
  annotations:
---

apiVersion: edgefs.rook.io/v1
kind: ISGW
metadata:
  name: isgw-capture          # Inter-Segment Gateway link for fully replicated data (pictures)
  namespace: rook-edgefs-aggr
spec:
  direction: "send+receive"   # I/O flow direction: send, receive or send-receive
  remoteURL: "ccow://rook-edgefs-isgw-isgw-capture.rook-edgefs-mec1:14001"     # I/O flow with destination antoher EdgeFS cluster, pointing to ISGW endpoint service
  localAddr: 0.0.0.0:14001     # Endpoint listening port
  annotations:
---

apiVersion: edgefs.rook.io/v1
kind: S3                      # S3 gateway to access captured videos and streams from remote
metadata:
  name: s3-aggr
  namespace: rook-edgefs-aggr
spec:
  instances: 1
  #s3type: s3s                # s3 (default) for path style, s3s for buckets as DNS style
  serviceType: NodePort       # define ServiceType (default ClusterIP)
  externalPort: 30303         # define NodePort for HTTP port (default auto)
  secureExternalPort: 30443   # define NodePort for HTTPS port (default auto)
  #port: 4500                 # HTTP port (default is 9982 or 9983 for s3s)
  #securePort: 4501           # HTTPS port (default is 8443 or 8444 for s3s)
  #sslCertificateRef: ssl-secret

